_CONFIG["password"] = "" -- Empty strings means no password
_CONFIG["db.type"] = "mysql" -- mysql is recommended
_CONFIG["db.username"] = "root"
_CONFIG["db.password"] = "root"
_CONFIG["db.host"] = "127.0.0.1"
_CONFIG["db.port"] = "3306"
_CONFIG["db.autoreconnect"] = true
_CONFIG["db.dbname"] = "open_reallife"
_CONFIG["db.charset"] = "utf8"
